"""State management for the Deep Research Framework.

This module defines the state schema and utility functions for managing
research workflow state throughout the LangGraph execution.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional, TypedDict


class ResearchState(TypedDict):
    """TypedDict schema for research workflow state.
    
    This state is passed between nodes in the LangGraph workflow and tracks
    the complete research execution context.
    
    Attributes:
        original_query: The user's initial research question
        research_plan: List of sub-questions generated by the planner node
        gaps_identified: String describing missing information (empty if complete)
        retrieved_documents: List of documents with url, content, title, source_tool
        research_loop_count: Number of retrieval-reflection cycles executed
        final_report: Markdown-formatted report with citations
        tool_execution_log: List of tool execution records for debugging
        max_loops: Maximum allowed research iterations to prevent infinite loops
    """
    original_query: str
    research_plan: Optional[List[str]]
    gaps_identified: Optional[str]
    retrieved_documents: List[Dict[str, Any]]
    research_loop_count: int
    final_report: Optional[str]
    tool_execution_log: List[Dict[str, Any]]
    max_loops: int


def log_tool_success(
    state: ResearchState,
    node: str,
    tool_category: str,
    tool_name: str,
    metadata: Optional[Dict[str, Any]] = None
) -> None:
    """Add a successful tool execution to the state log.
    
    Args:
        state: The current research state
        node: Name of the node that executed the tool (e.g., "planner", "retrieval")
        tool_category: Category of tool (e.g., "search", "scraper", "llm")
        tool_name: Specific tool name (e.g., "tavily", "trafilatura")
        metadata: Optional additional information about the execution
    """
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "node": node,
        "tool_category": tool_category,
        "tool_name": tool_name,
        "success": True,
        "error_msg": None,
        "metadata": metadata or {}
    }
    state["tool_execution_log"].append(log_entry)


def log_tool_failure(
    state: ResearchState,
    node: str,
    tool_category: str,
    tool_name: str,
    error_msg: str,
    metadata: Optional[Dict[str, Any]] = None
) -> None:
    """Add a failed tool execution to the state log.
    
    Args:
        state: The current research state
        node: Name of the node that executed the tool (e.g., "planner", "retrieval")
        tool_category: Category of tool (e.g., "search", "scraper", "llm")
        tool_name: Specific tool name (e.g., "tavily", "trafilatura")
        error_msg: Description of the error that occurred
        metadata: Optional additional information about the execution
    """
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "node": node,
        "tool_category": tool_category,
        "tool_name": tool_name,
        "success": False,
        "error_msg": error_msg,
        "metadata": metadata or {}
    }
    state["tool_execution_log"].append(log_entry)
